trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: k8s-common
  - name: helmRepoName
    value: 'helm'
  - name: chartName 
    value: 'order'
  - name: helmChartPath 
    value: './storehelmchart/'
  - name: helmChartVersion
    value: $(Build.BuildId)
  - name: imageTag
    value: $(Build.BuildId)
  - name: imageName
    value: 'order'

stages:
  - stage: Build
    displayName: Docker Build and Push
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build nad push Docker Images
        steps:
          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: $(acrServiceConnection)
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/order-service/Dockerfile'
              tag: $(imageTag)

  - stage: HelmPackagePush
    displayName: Helm Package and Push
    jobs:
    - job: Helm
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: appTemplates/helm-push.yml
          parameters:
            imageTag: $(imageTag)
            helmChartPath: $(helmChartPath)
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            serviceConnection: $(serviceConnection)

  - stage: Dev_Deploy
    displayName: Deploy to AKS Dev
    dependsOn: HelmPackagePush
    jobs:
    - job: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      variables:
      - group: 'k8s-dev'
      steps:
        - template: appTemplates/deploy.yml
          parameters:
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            aksCluster: $(aksCluster)
            aksResourceGroup: $(aksResourceGroup) 
            serviceConnection: $(serviceConnection)
            environment: $(environment)
            namespace: $(namespace)

  - stage: Prod_Deploy
    displayName: Deploy to AKS Prod
    dependsOn: Dev_Deploy
    jobs:
    - job: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      variables:
      - group: 'k8s-prod'
      steps:
        - template: appTemplates/deploy.yml
          parameters:
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            aksCluster: $(aksCluster)
            aksResourceGroup: $(aksResourceGroup) 
            serviceConnection: $(serviceConnection)
            environment: $(environment)
            namespace: $(namespace)